### ISSUE TITLE
fragmentedOperation error

### ISSUE THREAD

**Issue by cstumph** [Techwraith/ribcage-preview#13]
Error stacktrace:
```
~/repos/getable/OrdEx (master) ☢ ribcage preview components/list-cell-supplier-location/
[atomify] Proxying: http://localhost:4000
[atomify] Access URLs:
 ------------------------------------------
       Local: http://localhost:4001/default
    External: http://10.0.1.21:4001/default
 ------------------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.21:3001
 ------------------------------------------
[atomify] Watching files...
[atomify] Bundle updated in 3223ms
File written to ../../../../../usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/lib/_bundle.js

/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222:18)
    at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:394:12)
    at Receiver.<anonymous> (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
```

**Comment by cstumph** [comment]
I removed the only import statement I had in my CSS and it seems to have stopped happening.

**Comment by cstumph** [comment]
Scratch that. It still happens, it's just exceedingly rare in that case.

**Comment by joeybaker** [comment]
woah… weird. This seems to be totally be in browser-sync.

I think it's related to https://github.com/websockets/ws/issues/366

**Comment by joeybaker** [comment]
@cstumph apparently, [browsersync 2.6.4 doesn't have this problem](https://github.com/websockets/ws/issues/366#issuecomment-99493906). If it keeps happening to you, we could pin BS to that version.
