### ISSUE TITLE
Crashing on file save

### ISSUE THREAD

**Issue by joeybaker** [Techwraith/ribcage-preview#5]
https://github.com/Techwraith/ribcage-preview/commit/2e584791259193fa81e26f0d1cc4593595c140c2#diff-168726dbe96b3ce427e7fedce31bb0bcR9 causes an uncaught error for me when saving `example/entry.css`

```

Live reload server listening on port 4001
Atomify server listening on port 4000

File written to ../../../../usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/lib/_bundle.js

child_process.js:945
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:998:11)
    at ChildProcess.spawn (child_process.js:945:11)
    at Object.exports.spawn (child_process.js:733:9)
    at Static.gzip (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/lib/static.js:167:17)
    at ready (/usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/lib/static.js:370:14)
    at /usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/lib/static.js:103:9
    at /usr/local/lib/node_modules/ribcage/node_modules/ribcage-preview/node_modules/atomify/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/bin/builder.js:219:7
    at fs.js:266:14
    at /usr/local/lib/node_modules/ribcage/node_modules/ribcage-gen/node_modules/hbs-dir/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:107:15)
Program ribcage preview components/input-field exited with code 8
```

**Comment by joeybaker** [comment]
Can't repro this anymore.
